name: "InMana CI Workflow"
on:
  push:
    branches:
      - "feature/*"
  pull_request:
    branches:
      - "develop"
      - "master"

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      db:
        image: postgres:11
        ports: ["5432:5432"]
        env:
          POSTGRES_PASSWORD: postgres
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - uses: actions/checkout@v2
      - uses: erlef/setup-beam@v1
        with:
          otp-version: "23.x"
          elixir-version: "1.11.x"
      - run: mix deps.get
      - run: mix test
